import { Observable } from 'rxjs';
export interface PcInterface {
     id?: string;
     archivo?: string;
     archivoPublico?: string;
     tipo?: number;
     local_x?: number;
     local_y?: number;
     global_x?: number;
     global_y?: string;
     gps_lng?: number;
     gps_lat?: number;
     temperatura?: number;
     temperatura_real?: number;
     temperaturaMedia?: number;
     img_left?: number;
     img_top?: number;
     img_width?: number;
     img_height?: number;
     img_x?: number;
     img_y?: number;
     local_id?: number;
     vuelo?: string;
     image_rotation?: number;
     informeId?: string;
     datetime?: number;
     severidad?: number;
     reparable?: boolean;
     color?: string;
     downloadUrl?: Observable<string | null>;
     downloadUrlString?: string;
     downloadUrlRjpg$?: Observable<string | null>;
     downloadUrlStringRjpg?: string;
     resuelto: boolean;
     irradiancia?: number;
     gradiente?: number;
     polygonCoords?: Array<Array<number>>;
}
